version: "3"

services:
  backup:
    image: b3vis/borgmatic
    volumes:
      - ./data/:/data:ro
      - ./borgmatic:/etc/borgmatic.d/
      - ./borgmatic/ssh:/root/.ssh:ro
    environment:
      BORG_PASSPHRASE:

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
    volumes:
      - ./data/db:/var/lib/mysql


  web:
    image: tuxgasy/dolibarr
    environment:
      DOLI_DB_HOST: mariadb
      DOLI_DB_USER: root
      DOLI_DB_PASSWORD: root
      DOLI_DB_NAME: dolibarr
      DOLI_URL_ROOT: 'http://0.0.0.0'
      PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
      DOLI_ADMIN_LOGIN: 'admin'
      DOLI_ADMIN_PASSWORD: 'mysuperhypersecretpasswordforadminacount'
    expose:
      - 80
    links:
      - mariadb
    volumes:
      - ./data/dolibarr:/var/www/