version: "3.8"

services:
  openvpn:
    image: kylemanna/openvpn
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - openvpn-data/conf:/etc/openvpn
    networks:
      - reverse_proxy
    labels:
      caddy: vpn.colman.com.br
      caddy.reverse_proxy: "{{upstreams}}"

networks:
  reverse_proxy:
    external: true

volumes:
  openvpn-data: