# dclint disable require-project-name-field
x-environment: &postal
  POSTAL_WEB_HOSTNAME: postal.colman.com.br
  POSTAL_SMTP_HOSTNAME: postal.colman.com.br
  MAIN_DB_HOST: mariadb
  MAIN_DB_USERNAME: postal
  MAIN_DB_PASSWORD: postal
  MESSAGE_DB_HOST: mariadb
  MESSAGE_DB_PASSWORD: postal
  DNS_MX_RECORDS: "mx1.postal.colman.com.br, mx2.postal.colman.com.br"
  DNS_SPF_INCLUDE: "spf.postal.colman.com.br"
  DNS_RETURN_PATH_DOMAIN: "rp.postal.colman.com.br"
  DNS_ROUTE_DOMAIN: "routes.postal.colman.com.br"
  DNS_TRACK_DOMAIN: "track.postal.colman.com.br"
  SMTP_FROM_ADDRESS: "postal@colman.com.br"
  WEB_SERVER_DEFAULT_BIND_ADDRESS: "0.0.0.0"

services:
  backup:
    image: b3vis/borgmatic:1.9
    volumes:
      - database:/data/database
      - postal-config:/data/postal
      - ssh:/root/.ssh/
    configs:
      - source: borgmatic-config-postal
        target: /etc/borgmatic.d/config.yaml
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON=0 1 * * * # Remove whe        n https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed

  mariadb:
    image: mariadb:lts
    volumes:
      - database:/var/lib/mysql
    environment:
      MARIADB_USER: postal
      MARIADB_PASSWORD: postal
      MARIADB_ROOT_PASSWORD: postal

  smtp:
    image: ghcr.io/postalserver/postal:3.3.4
    volumes:
      - postal-config:/config
    environment:
      <<: *postal
    ports:
      - '0.0.0.0:25:25'
    command: postal smtp-server
    cap_add:
      - NET_BIND_SERVICE
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/health" ]

  web:
    image: ghcr.io/postalserver/postal:3.3.4
    volumes:
      - postal-config:/config
    environment:
      <<: *postal
    networks:
      - caddy
      - default
    command: postal web-server
    labels:
      caddy: "postal.colman.com.br"
      caddy.reverse_proxy: "{{upstreams 5000}}"
  

  worker:
    image: ghcr.io/postalserver/postal:3.3.4
    volumes:
      - postal-config:/config
    environment:
      <<: *postal
    command: postal worker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/health" ]

networks:
  caddy:
    external: true

volumes:
  postal-config: {}
  database: {}
  ssh:
    external: true

configs:
  borgmatic-config-postal:
    external: true
