x-environment: &postal
  POSTAL_WEB_HOSTNAME: postal.colman.com.br
  POSTAL_SMTP_HOSTNAME: postal.colman.com.br
  MAIN_DB_HOST: mariadb
  MAIN_DB_USERNAME: postal
  MAIN_DB_PASSWORD: postal
  MESSAGE_DB_HOST: mariadb
  MESSAGE_DB_PASSWORD: postal
  DNS_MX_RECORDS: "mx1.postal.colman.com.br, mx2.postal.colman.com.br"
  DNS_SPF_INCLUDE: "spf.postal.colman.com.br"
  DNS_RETURN_PATH_DOMAIN: "rp.postal.colman.com.br"
  DNS_ROUTE_DOMAIN: "routes.postal.colman.com.br"
  DNS_TRACK_DOMAIN: "track.postal.colman.com.br"
  SMTP_FROM_ADDRESS: "postal@colman.com.br"
  WEB_SERVER_DEFAULT_BIND_ADDRESS: "0.0.0.0"


services:
  mariadb:
    image: mariadb
    environment:
      MARIADB_USER: postal
      MARIADB_PASSWORD: postal
      MARIADB_ROOT_PASSWORD: postal
    volumes:
      - database:/var/lib/mysql
  
  web:
    image: ghcr.io/postalserver/postal
    command: postal web-server
    environment:
      <<: *postal
    networks:
      - caddy
      - default
    volumes:
      - postal-config:/config
    labels:
      caddy: "postal.colman.com.br"
      caddy.reverse_proxy: "{{upstreams 5000}}"

  smtp:
    image: ghcr.io/postalserver/postal
    command: postal smtp-server
    environment:
      <<: *postal
    ports:
      - "25:25"
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - postal-config:/config
  
  
  worker:
    image: ghcr.io/postalserver/postal
    command: postal worker
    environment:
      <<: *postal
    volumes:
      - postal-config:/config
  
  backup:
    image: b3vis/borgmatic
    volumes:
      - database:/data/database
      - postal-config:/data/postal
      - ssh:/root/.ssh/
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON=0 1 * * * # Remove when https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed
    configs:
      - source: borgmatic-config-postal
        target: /etc/borgmatic.d/config.yaml

configs:
  borgmatic-config-postal:
    external: true

volumes:
  postal-config: { }
  database: { }
  ssh:
    external: true

networks:
  caddy:
    external: true
    
