version: '3.8'

name: curupira-monitoring

services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"  # Expose Prometheus Web UI
    depends_on:
      - snmp-exporter

  snmp-exporter:
    image: prom/snmp-exporter
    restart: always
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml:ro
    command:
      - "--config.file=/etc/snmp_exporter/snmp.yml"
    ports:
      - "9116:9116"  # SNMP Exporter Web UI (metrics)
  
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"  # Grafana Web UI
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data:
