name: curupira-monitoring
services:
  
  influxdb:
    image: influxdb:1.8
    restart: always
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influxdb-data:/var/lib/influxdb

  telegraf:
    image: telegraf:latest
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./snmp-mibs:/usr/share/snmp/mibs:ro  # Mount MIB files
    environment:
      - MIBS=ALL  # Enable MIBs
      - TELEGRAF_SNMP_MIBS=/usr/share/snmp/mibs  # Set MIB directory
      - SNMP_MIB_DIRS=/usr/share/snmp/mibs  # Ensure MIBs are loaded
      - INFLUXDB_DB=telegraf
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb-data:
  grafana-data:
