version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/mysql
    restart: unless-stopped
    env_file: config.env

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./data/wp:/var/www/html
    expose:
      - 80
    restart: unless-stopped
    env_file: config.env
    networks:
      - default
      - caddy
    labels:
      caddy: renata.colman.com.br
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true