version: "3.7"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy_data:/data
      - ../colmans-cloud/data/nextcloud:/var/www/html
      - ../colmans-cloud/data/user_data:/var/user_data
      - ../colmans-cloud/data/apps:/var/www/html/apps
      - ../colmans-cloud/data/custom_apps:/var/www/html/custom_apps
    restart: unless-stopped

networks:
  caddy:
    external: true
