version: "3.8"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - reverse_proxy
    environment:
      - CADDY_INGRESS_NETWORKS=reverse_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    deploy:
      labels:
        caddy.email: caddy@colman.com.br
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: "0.1"
          memory: "200M"
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O-", "http://localhost:2019/metrics" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  reverse_proxy:
    external: true

volumes:
  caddy_data: { }