version: "3.8"

services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - ./data:/app/data
    expose:
      - 5005
    environment:
      PASSWORD: pw
    restart: unless-stopped
    labels:
      caddy: hub.colman.com.br
      caddy.reverse_proxy: "{{upstreams 5005}}"
    networks:
      - caddy

networks:
  caddy:
    external: true