version: "3.8"

services:
  postgres:
    env_file: configuration.env
    image: postgres
    expose:
      - 5432
  singlelink:
    env_file: configuration.env
    build: dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"