version: "3.8"

services:
  redmine:
    image: redmine:5
    environment:
      - REDMINE_DB_MYSQL=db
      - REDMINE_DB_PASSWORD
      - REDMINE_SECRET_KEY_BASE
    networks:
      - reverse_proxy
      - default
    labels:
      caddy: redmine.colman.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=redmine

networks:
  reverse_proxy:
    external: true