# dclint disable require-project-name-field
services:

  backup:
    image: b3vis/borgmatic:1.9
    volumes:
      - database:/data/database
      - redmine:/data/redmine
      - ssh:/root/.ssh/
    configs:
      - source: borgmatic-config-redmine
        target: /etc/borgmatic.d/config.yaml
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON=0 1 * * * # Remove when https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed

  database:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=redmine
      - MYSQL_USER=redmine

  redmine:
    image: redmine:6
    depends_on:
      - database
    environment:
      - REDMINE_DB_MYSQL=database
      - REDMINE_DB_PASSWORD
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_SECRET_KEY_BASE
    networks:
      - caddy
      - default
    labels:
      caddy: redmine.colman.com.br
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  caddy:
    external: true

volumes:
  redmine: {}
  database: {}
  ssh:
    external: true

configs:
  borgmatic-config-redmine:
    external: true
