# dclint disable require-project-name-field
services:
  borgmatic:
    image: b3vis/borgmatic:2.0
    volumes:
      - database:/data/database
      - redmine:/data/redmine
      - redmine-files:/data/redmine/files
      - ssh:/root/.ssh/
    configs:
      - source: borgmatic-config-redmine
        target: /etc/borgmatic.d/config.yaml
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON=0 1 * * * # Remove when https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed

  database:
    image: mysql:9
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=redmine
      - MYSQL_USER=redmine
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci

  redmine:
    image: redmine:6.0.3
    depends_on:
      - database
    environment:
      - REDMINE_DB_PASSWORD
      - REDMINE_SECRET_KEY_BASE
      - REDMINE_DB_MYSQL=database
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_ENCODING=utf8mb4
    networks:
      - caddy
      - default
    volumes:
      - redmine:/usr/src/redmine
      - redmine-files:/usr/src/redmine/files
    labels:
      caddy: redmine.colman.com.br
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  caddy:
    external: true

volumes:
  redmine: {}
  redmine-files: {}
  database: {}
  ssh:
    external: true

configs:
  borgmatic-config-redmine:
    external: true
