services:
  prometheus:
    image: prom/prometheus
    environment:
      PROMETHEUS_CONFIG: >
        global:
          scrape_interval: 15s
        scrape_configs:
          - job_name: "node"
            static_configs:
              - targets: ["node-exporter:9100"]
    labels:
      caddy: prometheus.colman.com.br
      caddy.reverse_proxy: "{{upstreams 9090}}"

  alertmanager:
    image: prom/alertmanager
    restart: always
    environment:
      ALERTMANAGER_CONFIG: >
        global:
          smtp_smarthost: "smtp.example.com:587"
          smtp_from: "alerts@example.com"
          smtp_auth_username: "your-email@example.com"
          smtp_auth_password: "your-email-password"
        route:
          receiver: "email"
        receivers:
          - name: "email"
            email_configs:
              - to: "alerts@example.com"
        

  node-exporter:
    image: prom/node-exporter
    restart: always

networks:
  default:
    external: true
    name: caddy