version: "3.7"

services:
  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    ports:
      - "443:443/tcp"
      - "53:53/tcp"
      - "67:67"
      - "53:53/udp"
      - "80:80/tcp"
    env_file: config.env
    environment:
      DNS1: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNS2: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNSSEC: "true" # Enable DNSSEC
    volumes:
      - ./etc_pihole-unbound:/etc/pihole:rw
      - ./etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    cap_add:
      - NET_ADMIN