version: "3.7"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - homebase
    environment:
      - CADDY_INGRESS_NETWORKS=homebase
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data


  pihole:
    image: cbcrowe/pihole-unbound:v5.8
    networks:
      - homebase
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - DNS1=127.0.0.1#5335
      - DNS2=127.0.0.1#5335
      - DNSSEC="true"
      - TZ=America/Sao_Paulo
      - WEBPASSWORD
    labels:
      caddy: pi.hole
      caddy.reverse_proxy: "{{upstreams}}"


volumes:
  caddy_data:

networks:
  homebase:
    external: true