version: "3.7"

services:
  pihole:
    image: cbcrowe/pihole-unbound:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - DNS1=127.0.0.1#5335
      - DNS2=127.0.0.1#5335
      - DNSSEC="true"
      - TZ=America/Montreal
      - WEBPASSWORD
