version: "3.9"

services:
  database:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD
    env_file: config.env

  wordpress:
    image: wordpress:latest
    depends_on:
      - database
    volumes:
      - wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_PASSWORD
    networks:
      - default
      - caddy
    labels:
      caddy: teste.cintia.colman.com.br
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true

volumes:
  database: {}
  wordpress: {}