version: "3.8"

services:
  mariadb:
    image: mariadb:10.7
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MARIADB_ROOT_PASSWORD
    volumes:
      - database:/var/lib/mysql
  
  redis:
    image: redis:alpine

  nextcloud:
    image: nextcloud:apache
    networks:
      - caddy
      - default
    environment:
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_TRUSTED_DOMAINS
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_SECURE
      - SMTP_AUTH_TYPE
      - SMTP_NAME
      - SMTP_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MARIADB_ROOT_PASSWORD
      - MAIL_FROM_ADDRESS=no-reply
      - MAIL_DOMAIN=colman.com.br
      - REDIS_HOST=redis
      - MYSQL_HOST=mariadb
      - TRUSTED_PROXIES=95.217.46.244
      - NC_default_phone_region=BR
    volumes:
      - nextcloud:/var/www/html
      - /hdd/nextcloud-data/data:/var/www/html/data
    depends_on:
      - mariadb
      - redis
    cap_add:
      - SYS_ADMIN
    labels:
      caddy: "cloud.colman.com.br"
      caddy.reverse_proxy: "{{upstreams}}"
      caddy.header: /*
      caddy.header.Strict-Transport-Security: "max-age=15552000"
      caddy.rewrite_0: /.well-known/carddav /remote.php/dav
      caddy.rewrite_1: /.well-known/caldav /remote.php/dav

  collabora:
    image: collabora/code
    networks:
      - caddy
    cap_add:
      - MKNOD
    environment:
      - username
      - password
      - dictionaries=en_GB en_US pt_BR
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
      - DONT_GEN_SSL_CERT=true
      - domain=cloud.colman.com.br
    labels:
      caddy: collabora.colman.com.br
      caddy.reverse_proxy: "{{upstreams 9980}}"

  cron:
    image: nextcloud:apache
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - mariadb
      - redis

  backup:
    image: b3vis/borgmatic
    volumes:
      - database:/data/database
      - nextcloud:/data/nextcloud
      - /hdd/nextcloud-data/data:/data/nextcloud/data
      - ssh:/root/.ssh/
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON=0 1 * * * # Remove when https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed
    configs:
      - source: borgmatic-config-nextcloud
        target: /etc/borgmatic.d/config.yaml

configs:
  borgmatic-config-nextcloud:
    external: true

networks:
  caddy:
    external: true

volumes:
  database:
  nextcloud:
  ssh:
    external: true