# dclint disable require-project-name-field
services:
  backup:
    image: b3vis/borgmatic:1.9
    volumes:
      - database:/data/database
      - nextcloud:/data/nextcloud
      - /hdd/nextcloud-data/data:/data/nextcloud/data
      - ssh:/root/.ssh/
    configs:
      - source: borgmatic-config-nextcloud
        target: /etc/borgmatic.d/config.yaml
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON=0 1 * * * # Remove when https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed

  collabora:
    image: collabora/code:24.04.11.1.1
    environment:
      - username
      - password
      - dictionaries=en_GB en_US pt_BR
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
      - DONT_GEN_SSL_CERT=true
      - domain=cloud.colman.com.br
    networks:
      - caddy
    labels:
      caddy: collabora.colman.com.br
      caddy.reverse_proxy: "{{upstreams 9980}}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9980/" ]

  cron:
    image: nextcloud:apache
    depends_on:
      - mariadb
      - redis
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/status.php" ]
  
  mariadb:
    image: mariadb:lts
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MARIADB_ROOT_PASSWORD
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]

  nextcloud:
    image: nextcloud:apache
    depends_on:
      - mariadb
      - redis
    volumes:
      - nextcloud:/var/www/html
      - /hdd/nextcloud-data/data:/var/www/html/data
    environment:
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_TRUSTED_DOMAINS
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_SECURE
      - SMTP_AUTH_TYPE
      - SMTP_NAME
      - SMTP_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MARIADB_ROOT_PASSWORD
      - OPCACHE_MEMORY_CONSUMPTION=256
      - OPCACHE_MAX_ACCELERATED_FILES=10000
      - MAIL_FROM_ADDRESS=no-reply
      - MAIL_DOMAIN=colman.com.br
      - REDIS_HOST=redis
      - MYSQL_HOST=mariadb
      - TRUSTED_PROXIES=95.217.46.244
      - NC_default_phone_region=BR
    networks:
      - caddy
      - default
    labels:
      caddy: "cloud.colman.com.br"
      caddy.reverse_proxy: "{{upstreams}}"
      caddy.header: /*
      caddy.header.Strict-Transport-Security: "max-age=15552000"
      caddy.rewrite_0: /.well-known/carddav /remote.php/dav
      caddy.rewrite_1: /.well-known/caldav /remote.php/dav
    cap_add:
      - SYS_ADMIN
    healthcheck:
      test: curl -sSf 'http://localhost/status.php' | grep '"installed":true' | grep '"maintenance":false' | grep '"needsDbUpgrade":false' || exit 1

  redis:
    image: redis:7-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

networks:
  caddy:
    external: true

volumes:
  database:
  nextcloud:
  ssh:
    external: true

configs:
  borgmatic-config-nextcloud:
    external: true
