version: "3"

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro`
    privileged: true
    restart: always
    ports:
      - "8123:8123"

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    volumes:
      - mosquitto:/mosquitto/

volumes:
  config: {}
  mosquitto: {}