version: "3"
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro`
    privileged: true
    network_mode: host
    labels:
      caddy: home.assistant.local
      caddy.reverse_proxy: "{{upstreams 8123}}"

  mosquitto:
    image: eclipse-mosquitto
    network_mode: host

volumes:
  config: {}

networks:
  homebase:
    external: true