version: "3"

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: always
    volumes:
      - /run/udev:/run/udev:ro
      - zigbee2mqtt:/app/data
    ports:
      - "8080:8080"
    devices:
      - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231007163002-if00:/dev/ttyACM0
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro`
    privileged: true
    restart: always
    ports:
      - "8123:8123"

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    volumes:
      - mosquitto:/mosquitto/

volumes:
  config: {}
  mosquitto: {}
  zigbee2mqtt: {}