version: "3.8"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    labels:
      caddy: ritalee.colman.com.br
      caddy.reverse_proxy: "https://127.0.0.1:8000"
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: "0.1"
          memory: "200M"

networks:
  caddy:
    external: true

volumes:
  caddy_data: { }