version: "3.8"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp" # HTTP/3 Support
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    deploy:
      labels:
        caddy_0.email: caddy@colman.com.br
        caddy_1: ritalee.colman.com.br
        caddy_1.reverse_proxy: portainer:9000
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: "0.1"
          memory: "200M"
    healthcheck:
      test: ["CMD", "/bin/caddy", "version"]      
networks:
  caddy:
    external: true

volumes:
  caddy_data: { }