version: "3.9"

services:
  database:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD

  wordpress:
    image: wordpress:latest
    depends_on:
      - database
    volumes:
      - wordpress:/var/www/html
      - php-config:/usr/local/etc/php/conf.d
    environment:
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_PASSWORD
    networks:
      - default
      - reverse_proxy
    labels:
      caddy: best-temperature-to-vape-weed.com *.best-temperature-to-vape-weed.com
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  reverse_proxy:
    external: true

volumes:
  database: {}
  wordpress: {}
  php-config: {}