services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - diun-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker  # 👈 Bind mount docker binary from host
    environment:
      - TZ=America/Sao_Paulo
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=*/10 * * * *
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=false

      # ✅ Script notifier: now works
      - DIUN_NOTIF_SCRIPT=true
      - DIUN_NOTIF_SCRIPT_CMD=/usd/bin/docker
      - DIUN_NOTIF_SCRIPT_ARGS=service update --force "$DIUN_ENTRY_METADATA_CTN_NAMES"
    restart: always
    network_mode: host  # 👈 Required if not using host.docker.internal

volumes:
  diun-data:
