services:
  diun:
    image: crazymax/diun:latest
    volumes:
      - diun-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=UTC
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_SCHEDULE=0 */10 * * * *
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=false
      - DIUN_NOTIF_STDOUT=true
      - DIUN_NOTIF_COMMAND='{"cmd":"/bin/sh","args":["-c","docker service update --force $DIUN_ENTRY_NAME"]}'
    deploy:
      placement:
        constraints: [node.role == manager]