version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file: db.env
    volumes:
      - ./data/db:/var/lib/mysql

  redis:
    image: redis:alpine

  app:
    build: nextcloud
    networks:
      - caddy
      - default
    env_file:
    - nextcloud.env
    - db.env
    volumes:
      - ./data/nextcloud:/var/www/html
      - ./data/apps:/var/www/html/apps
      - ./data/custom_apps:/var/www/html/custom_apps
      - ./data/themes:/var/www/html/themes
      - ./data/config:/var/www/html/config
      - ./data/user_data:/var/user_data
      - ./custom.ini:/usr/local/etc/php-fpm.d/zz-custom.conf
    depends_on:
      - db
      - redis
    labels:
      caddy: "cloud.colman.com.br"
      caddy.root: "* /var/www/html"
      caddy.file_server: ""
      caddy.php_fastcgi: "{{upstreams 9000}}"
      caddy.redir_0: "/.well-known/carddav /remote.php/dav 301"
      caddy.redir_1: "/.well-known/caldav /remote.php/dav 301"
      caddy.header.Strict-Transport-Security: "max-age=31536000"


  collabora:
    image: collabora/code
    restart: always
    networks:
      - caddy
    cap_add:
      - MKNOD
    env_file: collabora.env
    labels:
      caddy: collabora.colman.com.br
      caddy.reverse_proxy: "{{upstreams 9980}}"

  backup:
    image: b3vis/borgmatic
    volumes:
      - ./data:/data:ro
      - ./borgmatic:/etc/borgmatic.d/
      - ./borgmatic/ssh:/root/.ssh:ro
    environment:
      BORG_PASSPHRASE: abcde


networks:
  caddy:
    external: true
