services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_config:/etc/prometheus/
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - monitoring
      - caddy
    labels:
      caddy: prometheus.ninho.local
      caddy.reverse_proxy: "{{upstreams 9090}}"
      caddy.tls: internal
      

  snmp-exporter:
    image: prom/snmp-exporter:latest
    volumes:
      - snmp_config:/etc/snmp_exporter/
    restart: unless-stopped
    networks:
      - monitoring
      - caddy
    labels:
      caddy: snmp-exporter.ninho.local
      caddy.reverse_proxy: "{{upstreams 9116}}"
      caddy.tls: internal
      

  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - monitoring
      - caddy
    labels:
      caddy: grafana.ninho.local
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.tls: internal
      

networks:
  monitoring:
  caddy:
    external: true

volumes:
  prometheus_data:
  prometheus_config:
  grafana_data:
  snmp_config:
