global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'synology-nas'
    static_configs:
      - targets: ['192.168.15.165']  # replace with your NAS IP
    metrics_path: /snmp
    params:
      module: [synology]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116  # Docker internal network address
