version: "3.7"
services:
  librespeed:
    image: ghcr.io/librespeed/speedtest:latest
    environment:
      - MODE=standalone
      - TZ=America/Sao_Paulo
      - TITLE=Colman's Libre Speed
      - PASSWORD
    labels:
      caddy: librespeed.colman.com.br
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true