version: "3.7"
services:
  librespeed:
    image: adolfintel/speedtest
    environment:
      - TZ=EST
      - TITLE=Colman's Libre Speed
      - TELEMETRY=true
      - ENABLE_ID_OBFUSCATION=true
      - REDACT_IP_ADDRESSES=true
      - EMAIL=privacy@colman.com.br
      - PASSWORD
    labels:
      caddy: librespeed.colman.com.br
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true