version: "3.7"
services:
  librespeed:
    image: adolfintel/speedtest
    env_file: config.env
    environment:
      - TZ=EST
      - CUSTOM_RESULTS=true
    labels:
      caddy: librespeed.colman.com.br
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - caddy

networks:
  caddy:
    external: true