version: "3.8"

services:
  database:
    image: mariadb:10
    volumes:
      - database:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD

  wordpress:
    image: wordpress:6
    depends_on:
      - database
    volumes:
      - wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_PASSWORD
    networks:
      - default
      - caddy
    labels:
      caddy: leonardo.colman.com.br *.leonardo.colman.com.br
      caddy.reverse_proxy: "{{upstreams 80}}"

  backup:
    image: b3vis/borgmatic
    volumes:
      - database:/data/database:ro
      - wordpress:/data/wordpress:ro
      - ssh:/root/.ssh/:ro
    environment:
      - BORG_PASSPHRASE
    configs:
      - source: borgmatic-config-nextcloud
        target: /etc/borgmatic.d/config.yaml
      - source: borgmatic-crontab-nextcloud
        target: /etc/borgmatic.d/crontab.txt

networks:
  caddy:
    external: true

volumes:
  database: {}
  wordpress: {}
  ssh:
    external: true