# dclint disable require-project-name-field
services:
  chrony:
    image: dockurr/chrony:4.6.1
    environment:
      NTP_SERVERS: "a.st1.ntp.br,b.st1.ntp.br"
      TZ: "America/Sao_Paulo"
    ports:
      - '0.0.0.0:123:123/udp'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "chronyc", "tracking" ]
