version: "3"

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - upload:/var/www/html/storage/upload
    networks:
      - default
      - reverse_proxy
    depends_on:
      - db
    labels:
      caddy: firefly.colman.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"

  db:
    image: mariadb
    restart: always
    volumes:
      - database:/var/lib/mysql
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME\" | crontab - && crond -f -L /dev/stdout"

volumes:
  upload:
  database:

networks:
  reverse_proxy:
    external: true
