version: "3.8"

services:
  redmine:
    image: redmine:5-alpine
    depends_on:
      - database
    environment:
      - REDMINE_DB_MYSQL=database
      - REDMINE_DB_PASSWORD
      - REDMINE_SECRET_KEY_BASE
    networks:
      - caddy
      - default
    labels:
      caddy: redmine.colman.com.br
      caddy.reverse_proxy: "{{upstreams 3000}}"
    volumes:
      - redmine:/usr/src/redmine
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]

  database:
    image: mysql:5
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]

  backup:
    image: b3vis/borgmatic
    volumes:
      - database:/data/database
      - redmine:/data/redmine
      - ssh:/root/.ssh/
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON="" # Remove when https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed
    configs:
      - source: borgmatic-config-redmine
        target: /etc/borgmatic.d/config.yaml

configs:
  borgmatic-config-redmine:
    external: true

networks:
  caddy:
    external: true

volumes:
  redmine: {}
  database: {}
  ssh:
    external: true