version: "3.7"

services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    ports:
      - "1194:1194/udp"
    restart: unless-stopped
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
