version: "3.8"

services:
  sftp:
    image: atmoz/sftp
    volumes:
      - media:/media/
      - /root/.ssh/authorized_keys:/home/leonardo/.ssh/keys/authorized_keys
    command: "leonardo::::media"
    ports:
      - "2222:22"
    labels:
      caddy: sftp.jellyfin.colman.com.br
      caddy.reverse_proxy: "{{upstreams 22}}"

  jellyfin:
    image: jellyfin/jellyfin
    volumes:
      - config:/config
      - cache:/cache
      - media:/media
    restart: "unless-stopped"
    networks:
      - reverse_proxy
    labels:
      caddy: jellyfin.colman.com.br
      caddy.reverse_proxy: "{{upstreams 8096}}"


networks:
  reverse_proxy:
    external: true

volumes:
  config: { }
  cache: { }
  media: { }