# dclint disable require-project-name-field
services:
  agent:
    image: portainer/agent:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global

  backup:
    image: b3vis/borgmatic:1.9
    volumes:
      - portainer_data:/data/portainer
      - ssh:/root/.ssh/
    configs:
      - source: borgmatic-config-portainer
        target: /etc/borgmatic.d/config.yaml
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON=0 1 * * * # Remove when https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed

  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.9.1-alpine
    environment:
      - LOG_LEVEL=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    ports:
      - mode: host
        target: 80
        published: 80
      - mode: host
        target: 443
        published: 443
        protocol: tcp
      - mode: host
        target: 443
        published: 443
        protocol: udp
    networks:
      caddy:
    healthcheck:
      test: [ "CMD", "/bin/caddy", "version" ]
    deploy:
      mode: global
      labels:
        caddy.email: caddy@colman.com.br
      placement:
        constraints:
          - node.role == manager

  portainer:
    image: portainer/portainer-ce:alpine
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '0.0.0.0:9443:9443'
    networks:
      - agent_network
      - caddy
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    labels:
      caddy: ritalee.colman.com.br
      caddy.reverse_proxy: "{{upstreams 9000}}"

networks:
  agent_network:
    driver: overlay
    attachable: true
  caddy:
    external: true

volumes:
  portainer_data:
  ssh:
    external: true
  caddy_data:


configs:
  borgmatic-config-portainer:
    external: true
