services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama

  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    networks:
      - caddy
      - default
    restart: unless-stopped
    volumes:
      - open-webui:/app/backend/data
    labels:
      caddy: "chatgpt.colman.com.br"
      caddy.reverse_proxy: "{{upstreams 8080}}"
    environment:
      OLLAMA_BASE_URLS: http://ollama:11434

volumes:
  ollama:
  open-webui:
    
networks:
  caddy:
    external: true