# dclint disable require-project-name-field
services:
  streak-stats:
    image: leocolman/github-readme-streak-stats:1.0.0
    environment:
      - TOKEN
    networks:
      - caddy
    labels:
      caddy: github-readme-streak-stats.colman.com.br
      caddy.reverse_proxy: "{{upstreams 9000}}"

networks:
  caddy:
    external: true
