services:

  borgmatic:
    image: b3vis/borgmatic:1.9
    volumes:
      - kuma-data:/data/kuma
      - ssh:/root/.ssh
    configs:
      - source: borgmatic-config-uptime-kuma
        target: /etc/borgmatic.d/config.yaml
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON=0 1 * * * # Remove when https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed
  
  disk-check:
    image: ubuntu:24.04
    # If you need to mount the host filesystem read-only:
    volumes:
      - /:/host:ro
    environment:
      - TOKEN
      - THRESHOLD=75
    entrypoint: ["/bin/bash", "-c"]
    command: |
      echo "=== Hello from inside the container ==="
      sleep 5

  uptime-kuma:
    image: louislam/uptime-kuma:1-alpine
    volumes:
      - kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - caddy
      - default
    labels:
      caddy: kuma.colman.com.br
      caddy.reverse_proxy: "{{upstreams 3001}}"

networks:
  caddy:
    external: true
volumes:
  kuma-data:
  ssh:
    external: true
configs:
  borgmatic-config-uptime-kuma:
    external: true
