services:
  uptime-kuma:
    image: louislam/uptime-kuma:1-alpine
    volumes:
      - kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - caddy
    restart: unless-stopped
    labels:
      caddy: kuma.colman.com.br
      caddy.reverse_proxy: "* {{upstreams 3001}}"
networks:
  caddy:
    external: true
volumes:
  kuma-data:
