version: "3.7"
services:
  librespeed:
    image: ghcr.io/librespeed/speedtest:latest-alpine
    environment:
      - MODE=standalone
      - TZ=America/Sao_Paulo
      - TITLE=Colman's Libre Speed
      - PASSWORD
    labels:
      caddy: librespeed.ritalee.colman.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - caddy
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://librespeed.ritalee.colman.com.br" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  caddy:
    external: true