version: "3.8"

volumes:
  taiga-media:
  taiga-conf:
  database:

services:
  back:
    image: dockertaiga/back:6
    depends_on:
      - db
      - events
    volumes:
      - taiga-media:/taiga-media
      - taiga-conf:/taiga-conf
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  front:
    image: dockertaiga/front:6
    networks:
      - default
      - reverse_proxy
    volumes:
      - taiga-conf:/taiga-conf
    environment:
      - TAIGA_URL=https://taiga.colman.com.br
      - TAIGA_WEBSOCKETS_URL=wss://taiga.colman.com.br
    labels:
      caddy: taiga.colman.com.br
      caddy.reverse_proxy: "{{upstreams 80}}"

  events:
    image: dockertaiga/events:6
    depends_on:
      - rabbit
    environment:
      - TAIGA_SECRET_KEY
      - RABBITMQ_USER
      - RABBITMQ_PASS

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - database:/var/lib/postgresql/data

  rabbit:
    image: dockertaiga/rabbit
    environment:
      - RABBITMQ_USER
      - RABBITMQ_PASS


networks:
  reverse_proxy:
    external: true