# dclint disable require-project-name-field
services:
  dns-server:
    image: technitium/dns-server:13.5.0
    volumes:
      - config:/etc/dns
    environment:
      - DNS_SERVER_DOMAIN=dns-server
    ports:
      - '0.0.0.0:53:53/udp'
      - '0.0.0.0:53:53/tcp'
    networks:
      - caddy
    restart: unless-stopped
    labels:
      caddy: dns.colman.com.br
      caddy.reverse_proxy: "{{upstreams 5380}}"
    hostname: dns-server
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000

networks:
  caddy:
    external: true

volumes:
  config:
