version: "3.8"

services:
  github-workflows-kts:
    image: krzema12/github-workflows-kt-jit-binding-server:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' -L http://localhost:8080 | grep -q 404" ]
      interval: 1m30s
      timeout: 10s
      retries: 3

    networks:
      - reverse_proxy
    labels:
      caddy: github-workflows-kt-bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"
    environment:
      - GITHUB_TOKEN

  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - reverse_proxy
    labels:
      caddy: jaeger.github-workflows-kt-bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 16686}}"
      caddy.basicauth: "* bcrypt"
      caddy.basicauth.admin: "JDJhJDEyJHdIU0tJTG45clVDcHQuUmdIN3dvd09ub2VqSDdhakkyL0ZkNnI5OS5XQ2NkTzdHSVNkYmpP"

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dozzle:/data
    networks:
      - reverse_proxy
    labels:
      caddy: logs.github-workflows-kt-bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_FILTER: label=caddy=github-workflows-kt-bindings.colman.com.br


networks:
  reverse_proxy:
    external: true

volumes:
  dozzle: {}