version: "3.8"

services:
  github-workflows-kts:
    image: krzema12/github-workflows-kt-jit-binding-server:latest
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' -L http://localhost:8080/status | grep -q 200" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - otel_collector
    networks:
      - reverse_proxy
    labels:
      caddy: bindings.krzeminski.it, github-workflows-kt-bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"
      dozzle: "yes"
    environment:
      - GITHUB_TOKEN

  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      reverse_proxy:
        aliases: ["jaeger", "traces_collector"]
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:16686 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - PROMETHEUS_QUERY_NAMESPACE=${PROMETHEUS_QUERY_NAMESPACE:-}
      - PROMETHEUS_QUERY_DURATION_UNIT=${PROMETHEUS_QUERY_DURATION_UNIT:-}
      - PROMETHEUS_QUERY_NORMALIZE_CALLS=true
      - PROMETHEUS_QUERY_NORMALIZE_DURATION=true
    labels:
      caddy: jaeger.github-workflows-kt-bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 16686}}"
      caddy.basic_auth: "* bcrypt"
      caddy.basic_auth.admin: "JDJhJDEyJHdIU0tJTG45clVDcHQuUmdIN3dvd09ub2VqSDdhakkyL0ZkNnI5OS5XQ2NkTzdHSVNkYmpP"

  otel_collector:
    image: otel/opentelemetry-collector-contrib:latest
    depends_on:
      - jaeger
    networks:
      - reverse_proxy
    configs:
      - source: otel_config
        target: /etc/otelcol/config.yaml

  prometheus:
    image: prom/prometheus:latest
    networks:
      - reverse_proxy
    labels:
      caddy: prometheus.github-workflows-kt-bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 9090}}"
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "
        global:
          scrape_interval:     15s
          evaluation_interval: 15s

        scrape_configs:
          - job_name: 'aggregated-trace-metrics'
            static_configs:
              - targets: ['jaeger:8889', 'otel_collector:8889']
        " > /etc/prometheus/prometheus.yml && \
        /bin/prometheus --config.file=/etc/prometheus/prometheus.yml

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dozzle:/data
    networks:
      - reverse_proxy
    labels:
      caddy: logs.github-workflows-kt-bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_FILTER: label=dozzle=yes

networks:
  reverse_proxy:
    external: true

configs:
  otel_config:
    external: true


volumes:
  dozzle: {}
