# dclint disable require-project-name-field
services:
  
  backup:
    image: b3vis/borgmatic:1.9
    volumes:
      - grafana:/data/grafana
      - prometheus:/data/prometheus
      - ssh:/root/.ssh/
    configs:
      - source: borgmatic-config-github-workflows-kt
        target: /etc/borgmatic.d/config.yaml
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON=0 1 * * * # Remove when https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed
  
  github-workflows-kt:
    image: krzema12/github-workflows-kt-jit-binding-server # dclint disable-line
    environment:
      - GITHUB_TOKEN
      - APP_PRIVATE_KEY
    networks:
      - prometheus
      - caddy
    labels:
      caddy: bindings.krzeminski.it
      caddy.reverse_proxy: "{{upstreams 8080}}"

  grafana:
    image: grafana/grafana:11.5.2
    networks:
      - prometheus
      - caddy
    labels:
      caddy: grafana.bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 3000}}"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SMTP_USER
      - GF_SMTP_PASSWORD
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=postal.colman.com.br
      - GF_SMTP_FROM_ADDRESS=no-reply@colman.com.br
      - GF_SMTP_FROM_NAME=Grafana GitHub Workflows Kt
      - GF_SMTP_SKIP_VERIFY=false

  prometheus:
    image: prom/prometheus:v3.2.1
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
    labels:
      caddy: prometheus.bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 9090}}"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    networks:
      - prometheus
      - caddy
    volumes:
      - prometheus:/prometheus

volumes:
  grafana:
  prometheus:
  ssh:
    external: true

networks:
  prometheus:
  caddy:
    external: true

configs:
  prometheus:
    external: true
  borgmatic-config-github-workflows-kt:
    external: true