# dclint disable require-project-name-field
services:
  github-workflows-kt:
    image: krzema12/github-workflows-kt-jit-binding-server # dclint disable-line
    environment:
      - GITHUB_TOKEN
    networks:
      - prometheus
      - caddy
    labels:
      caddy: bindings.krzeminski.it
      caddy.reverse_proxy: "{{upstreams 8080}}"

  grafana:
    image: grafana/grafana:11.5.0
    networks:
      - prometheus
      - caddy
    labels:
      caddy: grafana.bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 3000}}"

  prometheus:
    image: prom/prometheus:v3.1.0
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
    labels:
      caddy: prometheus.bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 9090}}"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    networks:
      - prometheus
      - caddy

networks:
  prometheus:

configs:
  prometheus:
    external: true
