# dclint disable require-project-name-field
services:
  
  backup:
    image: b3vis/borgmatic:2.0.2-fix
    volumes:
      - grafana:/data/grafana
      - prometheus:/data/prometheus
      - ssh:/root/.ssh/
    configs:
      - source: borgmatic-config-github-workflows-kt
        target: /etc/borgmatic.d/config.yaml
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON=0 1 * * * # Remove when https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed
  
  github-workflows-kt:
    image: krzema12/github-workflows-kt-jit-binding-server:latest # dclint disable-line
    environment:
      - APP_PRIVATE_KEY
      - APP_INSTALLATION_ID
      - APP_CLIENT_ID
    networks:
      - prometheus
      - caddy
    labels:
      caddy: bindings.krzeminski.it
      caddy.reverse_proxy: "{{upstreams 8080}}"
      diun.enable: "true"
    logging:
      driver: loki
      options:
        loki-url: http://loki:3100/loki/api/v1/push

  prometheus:
    image: prom/prometheus:v3.3.1
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
    labels:
      caddy: prometheus.bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 9090}}"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    networks:
      - prometheus
      - caddy
    volumes:
      - prometheus:/prometheus

  grafana:
    image: grafana/grafana:11.6.1
    networks:
      - prometheus
      - caddy
    labels:
      caddy: grafana.bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 3000}}"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SMTP_USER
      - GF_SMTP_PASSWORD
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=postal.colman.com.br:25
      - GF_SMTP_FROM_ADDRESS=no-reply@colman.com.br
      - GF_SMTP_FROM_NAME=Grafana GitHub Workflows Kt
      - GF_SMTP_SKIP_VERIFY=false

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - caddy
      - prometheus
    ports:
      - "127.0.0.1:3100:3100"
    
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - prometheus


volumes:
  grafana:
  prometheus:
  ssh:
    external: true

networks:
  prometheus:
  caddy:
    external: true

configs:
  prometheus:
    external: true
  borgmatic-config-github-workflows-kt:
    external: true