# dclint disable require-project-name-field
services:
  github-workflows-kts:
    image: krzema12/github-workflows-kt-jit-binding-server:latest # dclint disable-line
    environment:
      - GITHUB_TOKEN
    networks:
      - caddy
      - default
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -o /dev/null -w '%{http_code}' -L
            http://localhost:8080/status | grep -q 200"
        ]
    labels:
      caddy: bindings.krzeminski.it
      caddy.reverse_proxy: "{{upstreams 8080}}"
  
  otel-collector:
    image: otel/opentelemetry-collector:latest
    networks:
      caddy:
        aliases:
         - traces_collector
    command: [ "--config", "/etc/otel-config.yaml" ]
    configs:
      - source: otel_config
        target: /etc/otel-config.yaml


networks:
  caddy:
    external: true

configs:
  otel_config:
    external: true
