# dclint disable require-project-name-field
services:
  
  backup:
    image: b3vis/borgmatic:2.0.2-fix
    volumes:
      - grafana:/data/grafana
      - prometheus:/data/prometheus
      - ssh:/root/.ssh/
    configs:
      - source: borgmatic-config-github-workflows-kt
        target: /etc/borgmatic.d/config.yaml
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON=0 1 * * * # Remove when https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed
  
  github-workflows-kt:
    image: krzema12/github-workflows-kt-jit-binding-server:latest # dclint disable-line
    environment:
      - APP_PRIVATE_KEY
      - APP_INSTALLATION_ID
      - APP_CLIENT_ID
    networks:
      - prometheus
      - caddy
    labels:
      caddy: bindings.krzeminski.it
      caddy.reverse_proxy: "{{upstreams 8080}}"
      diun.enable: "true"

  grafana:
    image: grafana/grafana:11.6.1
    networks:
      - prometheus
      - caddy
    labels:
      caddy: grafana.bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 3000}}"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SMTP_USER
      - GF_SMTP_PASSWORD
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=postal.colman.com.br:25
      - GF_SMTP_FROM_ADDRESS=no-reply@colman.com.br
      - GF_SMTP_FROM_NAME=Grafana GitHub Workflows Kt
      - GF_SMTP_SKIP_VERIFY=false

  prometheus:
    image: prom/prometheus:v3.3.1
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
    labels:
      caddy: prometheus.bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 9090}}"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    networks:
      - prometheus
      - caddy
    volumes:
      - prometheus:/prometheus

  loki:
    image: grafana/loki:3.0.0
    command:
      - -config.file=/etc/loki/loki.yaml
    configs:
      - source: loki-config
        target: /etc/loki/loki.yaml
    networks:
      - prometheus
      - caddy
    labels:
      caddy: loki.bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 3100}}"
    volumes:
      - loki:/loki

  promtail:
    image: grafana/promtail:3.0.0
    depends_on:
      - loki
    command:
      - -config.file=/etc/promtail/promtail.yaml
    configs:
      - source: promtail-config
        target: /etc/promtail/promtail.yaml
    networks:
      - prometheus
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
  
volumes:
  grafana:
  prometheus:
  loki:
  ssh:
    external: true

networks:
  prometheus:
  caddy:
    external: true

configs:
  prometheus:
    external: true
  borgmatic-config-github-workflows-kt:
    external: true
  loki-config:
    external: true
  promtail-config:
    external: true