version: "3.8"

services:
  github-workflows-kts:
    image: krzema12/github-workflows-kt-jit-binding-server:latest
    deploy:
      replicas: 2
    networks:
      - reverse_proxy
    labels:
      caddy: github-workflows-kt-bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"
    environment:
      - GITHUB_TOKEN

  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - reverse_proxy
    labels:
      caddy: jaeger.github-workflows-kt-bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 16686}}"
      caddy.basicauth: "/ admin $2a$12$wHSKILn9rUCpt.RgH7wowOnoejH7ajI2/Fd6r99.WCcdO7GISdbjO"

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dozzle:/data
    networks:
      - reverse_proxy
    labels:
      caddy: logs.github-workflows-kt-bindings.colman.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_FILTER: label=caddy=github-workflows-kt-bindings.colman.com.br


networks:
  reverse_proxy:
    external: true

volumes:
  dozzle: {}