version: "3.8"

services:
  github-workflows-kts:
    image: krzema12/github-workflows-kt-script-generator-server:0.41.0
    networks:
      - reverse_proxy
    labels:
      caddy: github-workflows-kt.colman.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  reverse_proxy:
    external: true