{
 "title": "Main Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Business Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up[$__range]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "Top Requested Actions",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(5, label_join(sum by(name, owner, version) (increase(artifact_requests_total{file=~\".*\\\\.jar$\"}[$__range])), \"__name__\", \"/\", \"owner\", \"name\", \"version\"))",
     "legendFormat": "{{owner}}/{{name}}/{{version}}"
    }
   ]
  },
  {
   "title": "Requested Artifact Version Type",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(artifact_requests_total{version=~\"v[0-9]+$\", file=~\".*\\\\.jar$\"}[$__range]))",
     "legendFormat": "Major"
    },
    {
     "expr": "sum(increase(artifact_requests_total{version=~\"v[0-9]+\\\\.[0-9]+.*\", file=~\".*\\\\.jar$\"}[$__range]))",
     "legendFormat": "Specific"
    },
    {
     "expr": "sum(increase(artifact_requests_total{version!~\"v[0-9]+$|v[0-9]+\\\\.[0-9]+.*\", file=~\".*\\\\.jar$\"}[$__range]))",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(ktor_http_server_requests_seconds_count{status=\"500\"}[$__rate_interval]))\n  or vector(0)\n",
     "legendFormat": "Status 500"
    }
   ]
  },
  {
   "title": "File Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(artifact_requests_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(ktor_http_server_requests_seconds)",
     "legendFormat": "Time Taken by Request"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(process_cpu_usage[1m]) * system_cpu_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "cache_size", "legendFormat": "Cache Entries" },
    { "expr": "avg_over_time(cache_size[7d])", "legendFormat": "Average Over Last 7d" }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(cache_gets_total{result=\"hit\"}[$__range])) / sum(rate(cache_gets_total{}[$__range]))) * 100.0",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sum(jvm_memory_used_bytes)", "legendFormat": "Total Bytes" },
    {
     "expr": "sum(avg_over_time(jvm_memory_used_bytes[1h]))",
     "legendFormat": "Average Over Time[1h]"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    { "expr": "jvm_threads_states_threads", "legendFormat": "{{state}}" }
   ]
  }
 ]
}