# How the traces arrive to the OTel Collector, i.e. where the app
# should send them to.
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

# Where the processed traces and metrics should be sent to.
exporters:
  # For aggregated metrics.
  prometheus:
    endpoint: "0.0.0.0:8889"

  # For raw spans.
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

connectors:
  spanmetrics:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [spanmetrics, otlp]

    # The metrics pipeline receives generated span metrics from 'spanmetrics' connector
    # and pushes to Prometheus exporter, which makes them available for scraping on :8889.
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
