receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite, debug]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]