# Learn more about the OpenTelemetry Collector via
# https://opentelemetry.io/docs/collector/

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  
  # Prometheus receiver that scrapes the Collector’s own internal telemetry endpoint (port 8888)
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector-internal'
          scrape_interval: 5s
          static_configs:
            - targets: [ '0.0.0.0:8888' ]  # Scrape the Collector's self-telemetry

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
    logs:
      level: debug  # Set log level to debug

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, debug]
      
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [debug, prometheus]
      
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]