global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['traces_collector:8889']
        
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269'] # Jaeger Prometheus metrics endpoint