version: "3.8"

services:
  postgres:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "jopiter"
      POSTGRES_DB: "jopiter"

  jopiter:
    image: jopiterapp/jopiter-backend:latest
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jopiter
    networks:
      - default
      - reverse_proxy
    labels:
      caddy: v4.backend.jopiter.app
      caddy.reverse_proxy: "{{upstreams 5000}}"

  backup:
    image: b3vis/borgmatic
    volumes:
      - postgres-data:/data/database:ro
      - ssh:/root/.ssh/:ro
    environment:
      - BORG_PASSPHRASE
    configs:
      - source: borgmatic-config-jopiter
        target: /etc/borgmatic.d/config.yaml
      - source: borgmatic-crontab-jopiter
        target: /etc/borgmatic.d/crontab.txt

volumes:
  postgres-data:
  ssh:
    external: true

configs:
  borgmatic-config-jopiter:
    external: true
  borgmatic-crontab-jopiter:
    external: true

networks:
  default:
  reverse_proxy:
    external: true