version: "3.8"

services:
  backup:
    image: b3vis/borgmatic
    volumes:
      - ./data/:/data:ro
      - ./borgmatic:/etc/borgmatic.d/
      - ./borgmatic/ssh:/root/.ssh:ro
    environment:
      BORG_PASSPHRASE: abcde
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
      - ./data/:/app/public/
    expose:
      - 80
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      caddy: hub.colman.com.br
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - caddy

networks:
  caddy:
    external: true