version: "3.8"

services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
      - ./data/conf.yml:/app/public/conf.yml
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      caddy: hub.colman.com.br
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - caddy

networks:
  caddy:
    external: true