version: "3.8"

services:
  searxng:
    image: searxng/searxng:latest
    networks:
      - reverse_proxy
    environment:
      SEARXNG_BASE_URL: "https://searxng.colman.com.br"
    labels:
      caddy: searxng.colman.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"


networks:
  reverse_proxy:
    external: true
