version: "3.8"

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    volumes:
      - config:/config
      - modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
      - SERVERURL=wireguard.colman.com.br
      - PEERS
    networks:
      - reverse_proxy
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      caddy: wireguard.colman.com.br
      caddy.reverse_proxy: "{{upstreams}}"

networks:
  reverse_proxy:
    external: true

volumes:
  config:
  modules:
