version: "3.8"

services:
  redmine:
    image: redmine:5.1.1
    depends_on:
      - db
    environment:
      - REDMINE_DB_MYSQL=db
      - REDMINE_DB_PASSWORD
      - REDMINE_SECRET_KEY_BASE
    networks:
      - reverse_proxy
      - default
    labels:
      caddy: redmine.colman.com.br
      caddy.reverse_proxy: "{{upstreams 3000}}"
    volumes:
      - attachments:/usr/src/redmine/files
      - plugins:/usr/src/redmine/plugins

  db:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=redmine

  backup:
    image: b3vis/borgmatic
    volumes:
      - attachments:/data/attachments
      - plugins:/data/plugins
      - database:/data/database
      - ssh:/root/.ssh/:ro
    environment:
      - BORG_PASSPHRASE
    configs:
      - source: borgmatic-config-redmine
        target: /etc/borgmatic.d/config.yaml
      - source: borgmatic-crontab-redmine
        target: /etc/borgmatic.d/crontab.txt

configs:
  borgmatic-config-redmine:
    external: true
  borgmatic-crontab-redmine:
    external: true

networks:
  reverse_proxy:
    external: true

volumes:
  database: {}
  attachments: {}
  plugins: {}
  ssh:
    external: true