version: "3.8"

services:
  searxng:
    image: searxng/searxng:latest
    networks:
      - caddy
    environment:
      SEARXNG_BASE_URL: "https://searxng.colman.com.br"
    labels:
      caddy: searxng.colman.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://0.0.0.0:8080/healthz"]
networks:
  caddy:
    external: true
